"use server";
// Auto-generated by Cobra (deterministic, 0 tokens). UPLOAD-TICKET ACTION.
// The ONLY storage-specific Server Action. Your upload island calls getUploadTicket
// to obtain a presigned ticket, uploads the file with uploadToBucket() from
// "@/lib/storage/upload-client", then stores the returned public URL on a row via
// your NORMAL create/update action. NEVER throws (returns a discriminated result).

import { createUploadTicket } from "@/lib/storage/upload";
import type { UploadTicketInput, UploadTicketResult } from "@/lib/storage/upload";
import { createClient } from "@/lib/supabase/server";

export async function getUploadTicket(input: UploadTicketInput): Promise<UploadTicketResult> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Connectez-vous pour téléverser un fichier." };
  return createUploadTicket(input);
}
