// Auto-generated by Cobra (deterministic, 0 tokens). AI CHAT ROUTE HANDLER.
// This is the /api/chat route. It calls the builder's
// AI proxy via the server-only streamChat client and returns the stream.
//
// You MAY edit this file (e.g. to gate on auth, prepend a system prompt, or
// transform messages) — it is the app's own route. The default passthrough is
// correct and working; only change what you need to.
import { type NextRequest } from "next/server";
import { streamChat, type AiModelAlias } from "@/lib/ai/client";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  // The messages + model come from the request body. Default to "balanced".
  const model = (body.model as AiModelAlias) || "balanced";
  const messages = Array.isArray(body.messages) ? body.messages : [];
  return streamChat({
    model,
    messages,
    system: typeof body.system === "string" ? body.system : undefined,
    signal: req.signal,
  });
}