// Auto-generated by Cobra (deterministic, 0 tokens). STORAGE CLIENT (server).
// This app holds NO AWS credentials. It asks the builder's storage proxy for a
// short-lived presigned S3 POST ticket (size + type capped at the S3 policy layer);
// the BROWSER then uploads directly to S3 with that ticket. Import this ONLY from a
// Server Action / Server Component / Route Handler — the token is server-only. The
// browser-side upload lives in "@/lib/storage/upload-client" (no secret).
//
// NEVER throws: returns a discriminated { ok } result.

const API_URL = (process.env.STORAGE_API_URL || "").replace(/\/+$/, "");
const API_TOKEN = process.env.STORAGE_API_TOKEN || "";
const APP_ID = process.env.NEXT_PUBLIC_APP_ID || "";

const NOT_CONFIGURED =
  "Téléversement indisponible (configuration serveur manquante). Réessayez plus tard.";
const AUTH_REDIRECT_ERROR =
  "Le service de téléversement a renvoyé une redirection d'authentification — vérifiez la configuration du proxy (STORAGE_API_URL / allowlist).";

export interface UploadTicketInput {
  /** Original filename — used to derive the extension. */
  filename?: string;
  /** MIME type. Must be an allowed type (images, pdf, mp4/webm, mp3/m4a). */
  contentType: string;
  /** Byte size, if known — lets the server reject an over-cap file before signing. */
  size?: number;
}

export interface UploadTicket {
  /** POST target (the S3 bucket URL). */
  url: string;
  /** Policy form fields — append these BEFORE the file. */
  fields: Record<string, string>;
  /** The public (CloudFront) URL to persist/display after a successful upload. */
  publicUrl: string;
  key: string;
  maxBytes: number;
}

export type UploadTicketResult =
  | { ok: true; ticket: UploadTicket }
  | { ok: false; error: string };

function proxyAuthBounced(res: Response): boolean {
  if (res.type === "opaqueredirect") return true;
  if (res.status >= 300 && res.status < 400) return true;
  const ct = res.headers.get("content-type") || "";
  return res.ok && !ct.includes("application/json");
}

/**
 * Ask the builder for a presigned upload ticket. Call from a Server Action, then
 * hand the ticket to the browser and upload with uploadToBucket() from
 * "@/lib/storage/upload-client". NEVER throws — check result.ok.
 */
export async function createUploadTicket(input: UploadTicketInput): Promise<UploadTicketResult> {
  if (!API_URL || !API_TOKEN || !APP_ID) return { ok: false, error: NOT_CONFIGURED };
  if (!input || typeof input.contentType !== "string" || !input.contentType.trim()) {
    return { ok: false, error: "Type de fichier manquant." };
  }
  try {
    const res = await fetch(API_URL + "/api/apps/storage/presign", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + API_TOKEN,
      },
      body: JSON.stringify({
        appId: APP_ID,
        filename: input.filename,
        contentType: input.contentType,
        size: input.size,
      }),
      redirect: "manual",
      cache: "no-store",
    });
    if (proxyAuthBounced(res)) return { ok: false, error: AUTH_REDIRECT_ERROR };
    const data: {
      url?: string;
      fields?: Record<string, string>;
      publicUrl?: string;
      key?: string;
      maxBytes?: number;
      error?: string;
    } = await res.json().catch(() => ({}));
    if (!res.ok || typeof data.url !== "string" || !data.fields || typeof data.publicUrl !== "string") {
      return { ok: false, error: data.error || "Échec de la préparation du téléversement (" + res.status + ")." };
    }
    return {
      ok: true,
      ticket: {
        url: data.url,
        fields: data.fields,
        publicUrl: data.publicUrl,
        key: typeof data.key === "string" ? data.key : "",
        maxBytes: typeof data.maxBytes === "number" ? data.maxBytes : 0,
      },
    };
  } catch {
    return { ok: false, error: "Service de téléversement injoignable. Réessayez plus tard." };
  }
}
