"use client";
// Auto-generated by Cobra (deterministic, 0 tokens). BROWSER UPLOAD HELPER.
// Safe to import from a "use client" component — holds NO secret. Uploads a File
// directly to S3 with a presigned POST ticket obtained from createUploadTicket()
// in a Server Action. NEVER throws.

export interface PresignedTicket {
  url: string;
  fields: Record<string, string>;
  publicUrl: string;
}

export type UploadResult = { ok: true; url: string } | { ok: false; error: string };

/**
 * Upload a File using a presigned POST ticket. Appends every policy field, then the
 * file LAST (S3 rejects the upload otherwise), and POSTs. Returns the public URL to
 * persist on success. NEVER throws — check result.ok.
 */
export async function uploadToBucket(ticket: PresignedTicket, file: File): Promise<UploadResult> {
  try {
    const form = new FormData();
    for (const [k, v] of Object.entries(ticket.fields)) form.append(k, v);
    form.append("file", file); // MUST be appended last
    const res = await fetch(ticket.url, { method: "POST", body: form });
    if (!res.ok) return { ok: false, error: "Échec du téléversement du fichier (" + res.status + ")." };
    return { ok: true, url: ticket.publicUrl };
  } catch {
    return { ok: false, error: "Téléversement interrompu. Réessayez." };
  }
}
