// Auto-generated by Cobra (deterministic, 0 tokens). AI CLIENT (server-only).
// This app holds NO provider key. It calls the builder's AI proxy
// (/api/apps/ai/chat) with the shared secret; the proxy holds the single
// OpenRouter key, resolves the model ALIAS to the real model, streams a
// plain-text stream back, and records the real usage. Import
// this ONLY from a Route Handler / Server Action / Server Component — the
// token is server-only.
//
// The browser fetches /api/chat and reads the plain-text stream directly
// the app's OWN route handler (app/api/chat/route.ts), which calls streamChat.

const API_URL = (process.env.AI_API_URL || "").replace(/\/+$/, "");
const API_TOKEN = process.env.AI_API_TOKEN || "";
const APP_ID = process.env.NEXT_PUBLIC_APP_ID || "";

const NOT_CONFIGURED =
  "IA indisponible (configuration serveur manquante). Réessayez plus tard.";
const AUTH_REDIRECT_ERROR =
  "Le service IA a renvoyé une redirection d'authentification — vérifiez la configuration du proxy (AI_API_URL / allowlist).";

/** The stable, app-facing model aliases. Never raw model ids. */
export type AiModelAlias = "fast" | "balanced" | "thinking";

/** A chat message in the OpenAI shape the proxy accepts. */
export interface AiChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface StreamChatOptions {
  /** Which alias to route to (the proxy enforces it). */
  model: AiModelAlias;
  messages: AiChatMessage[];
  /** Optional system prompt. */
  system?: string;
  /** Forward the browser's abort signal so a stop cancels the upstream stream. */
  signal?: AbortSignal;
}

/**
 * True when the proxy response looks like an auth-redirect bounce (Clerk
 * redirected the machine-to-machine call to /login). The proxy is allowlisted,
 * but this guards against a misconfigured allowlist returning a 200 HTML page.
 * CRITICAL: with `redirect: "manual"` a 3xx does NOT surface as a 3xx status —
 * `fetch` returns an OPAQUE response with `type: "opaqueredirect"` and
 * `status: 0`. Returning that raw Response from a Next route handler throws
 * `NextResponse.rewrite() ... not supported` and 500s the route. So an
 * opaque redirect MUST be caught here and turned into a clean JSON error.
 */
function proxyAuthBounced(res: Response): boolean {
  if (res.type === "opaqueredirect") return true;
  if (res.status === 0 || (res.status >= 300 && res.status < 400)) return true;
  const ct = res.headers.get("content-type") || "";
  return res.status === 200 && !ct.includes("application/json") && !ct.includes("text/event-stream") && !ct.includes("text/plain");
}

/**
 * Stream a chat completion from the builder's AI proxy. Returns a FRESH
 * `Response` (a plain-text stream) for the Route Handler to
 * return directly to the browser. NEVER throws — on a setup/network failure it
 * returns a `Response` whose body is a JSON `{ error }` so the caller can
 * surface it. Pass the browser's `signal` so a Stop button cancels upstream.
 *
 * IMPORTANT: we RE-WRAP the upstream Response as `new Response(res.body, ...)`,
 * never return the raw fetch Response. A fetch Response carries internal state
 * (opaque type, cached-url, etc.) that Next's route-handler runtime can't
 * serialize — returning it verbatim throws `NextResponse.rewrite() ... not
 * supported` and 500s the route. A fresh Response wrapping the upstream stream
 * is a plain, serializable object the runtime streams cleanly.
 */
export async function streamChat(opts: StreamChatOptions): Promise<Response> {
  if (!API_URL || !API_TOKEN || !APP_ID) {
    return new Response(JSON.stringify({ error: NOT_CONFIGURED }), {
      status: 503,
      headers: { "Content-Type": "application/json" },
    });
  }
  let res: Response;
  try {
    res = await fetch(API_URL + "/api/apps/ai/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + API_TOKEN,
      },
      body: JSON.stringify({
        appId: APP_ID,
        model: opts.model,
        messages: opts.messages,
        ...(opts.system ? { system: opts.system } : {}),
      }),
      redirect: "manual",
      cache: "no-store",
      signal: opts.signal,
    });
  } catch {
    return new Response(JSON.stringify({ error: "Service IA injoignable. Réessayez plus tard." }), {
      status: 502,
      headers: { "Content-Type": "application/json" },
    });
  }
  if (proxyAuthBounced(res)) {
    return new Response(JSON.stringify({ error: AUTH_REDIRECT_ERROR }), {
      status: 502,
      headers: { "Content-Type": "application/json" },
    });
  }
  // Re-wrap the upstream stream into a FRESH Response with a CLEAN header set.
  // Two reasons we do NOT copy `res.headers` wholesale:
  //   1. A fetch Response carries internal state Next's route runtime can't
  //      serialize (the original "NextResponse.rewrite() not supported" 500).
  //   2. CRITICAL: the builder's Clerk middleware injects `x-middleware-rewrite`
  //      / `x-middleware-next` headers into the proxy response. If those leak
  //      into THIS route handler's response, Next.js interprets them as a
  //      middleware rewrite instruction and throws `NextResponse.rewrite() was
  //      used in a route handler` → 500. Copying only the headers the client
  //      needs strips the middleware headers and fixes it.
  const ct = res.headers.get("content-type") || "text/plain; charset=utf-8";
  const headers: Record<string, string> = {
    "Content-Type": ct,
    "Cache-Control": res.headers.get("cache-control") || "no-cache, no-transform",
    "Connection": "keep-alive",
  };
  const aliasH = res.headers.get("x-ai-model-alias");
  if (aliasH) headers["X-AI-Model-Alias"] = aliasH;
  return new Response(res.body, { status: res.status, headers });
}

/** A model option for the app's UI picker. */
export interface AiModelOption {
  alias: AiModelAlias;
  label: string;
  guidance: string;
}

/** The catalog the app may render in its model picker (labels only — no ids). */
export const AI_MODELS: AiModelOption[] = [
  { alias: "fast", label: "Rapide", guidance: "Tâches triviales : classification, résumé, questions simples." },
  { alias: "balanced", label: "Équilibré", guidance: "Tâches générales : rédaction, traduction, assistance standard." },
  { alias: "thinking", label: "Réfléchi", guidance: "Tâches nécessitant du raisonnement : planification, code, logique." },
];

/** Aggregated AI usage for the app's dashboard (reads the proxy ledger). */
export interface AiUsageSummary {
  totalTokens: number;
  costUsd: number;
  costEstimated: boolean;
  calls: number;
  spendCapUsd: number;
  remainingUsd: number;
}

/** Read this app's aggregated AI usage + remaining budget from the proxy. */
export async function getAiUsage(): Promise<AiUsageSummary | { error: string }> {
  if (!API_URL || !API_TOKEN || !APP_ID) return { error: NOT_CONFIGURED };
  try {
    const res = await fetch(API_URL + "/api/apps/ai/usage?appId=" + encodeURIComponent(APP_ID), {
      headers: { Authorization: "Bearer " + API_TOKEN },
      cache: "no-store",
    });
    if (!res.ok) return { error: "Usage IA indisponible (" + res.status + ")." };
    return (await res.json()) as AiUsageSummary;
  } catch {
    return { error: "Usage IA injoignable." };
  }
}