// Auto-generated by Cobra (deterministic, 0 tokens). PAYMENTS CLIENT.
// This app holds NO Stripe secret key. It calls the builder's payments backend
// (which owns the Stripe account) with a scoped, server-only app token. Import
// this ONLY from Server Actions / Server Components / Route Handlers — never
// from a "use client" component (the token is server-only).
//
// These helpers NEVER throw: they return a discriminated { ok } result, so an
// unguarded caller can't crash a Server Action or a Server Component. A proxy
// hiccup or a misconfigured env surfaces as { ok: false, error } to be rendered.

import { headers } from "next/headers";

const API_URL = (process.env.PAYMENTS_API_URL || "").replace(/\/+$/, "");
const API_TOKEN = process.env.PAYMENTS_API_TOKEN || "";
const APP_ID = process.env.NEXT_PUBLIC_APP_ID || "";

export interface CheckoutItem {
  /** Display name of the line item. */
  name: string;
  /** Unit price in the smallest currency unit (e.g. cents: 12.5€ -> 1250). Computed SERVER-SIDE from the authoritative price source — never from a client-sent total. */
  amount: number;
  quantity?: number;
  currency?: string;
}

export interface CreateCheckoutInput {
  items: CheckoutItem[];
  /** "payment" (one-off) or "subscription". Default "payment". */
  mode?: "payment" | "subscription";
  /** OPTIONAL. The app's own origin. Leave it UNSET — this client resolves the
   *  origin SERVER-SIDE from the request headers (works on localhost, any port,
   *  and in production). Only pass it to force a specific absolute origin. */
  origin?: string;
  /** Return path on success. Default "/checkout/success". */
  successPath?: string;
  /** Return path on cancel. Default "/checkout/cancel". */
  cancelPath?: string;
  customerEmail?: string;
  /** string->string metadata echoed back on the session (e.g. { orderId }). */
  metadata?: Record<string, string>;
}

export type CheckoutResult =
  | { ok: true; url: string; sessionId: string }
  | { ok: false; error: string };

/**
 * The ACTION-facing result: what your `app/actions/*` checkout Server Action
 * returns to the buy-button island — a hosted-checkout `url` OR an `error`.
 * ANNOTATE the action explicitly `Promise<CheckoutActionResult>` and import this
 * type. An INFERRED return type is the trap: if the action `redirect()`s (returns
 * `never`) or returns a wrong shape, the mismatch surfaces as an UNFIXABLE
 * "Property 'url' does not exist on type 'never'" in the CONSUMER (the button),
 * where heal can never repair it. The explicit annotation pins the contract to
 * THIS type, so tsc reports the error in the ACTION file — the file that is wrong.
 * The action MUST `return { url }` / `return { error }` — it must NOT redirect to
 * Stripe itself; the client island does `window.location.href = r.url`.
 */
export type CheckoutActionResult = { url: string } | { error: string };

export type CheckoutStatusResult =
  | {
      ok: true;
      paid: boolean;
      status: string | null;
      amountTotal: number | null;
      currency: string | null;
      customerEmail: string | null;
      metadata: Record<string, string>;
    }
  | { ok: false; error: string };

const NOT_CONFIGURED =
  "Paiements indisponibles (configuration serveur manquante). Réessayez plus tard.";

const AUTH_REDIRECT_ERROR =
  "Le service de paiement a renvoyé une redirection d'authentification — vérifiez la configuration du proxy (PAYMENTS_API_URL / allowlist).";

/**
 * Detect a proxy that bounced our request to a login/auth page instead of
 * answering the JSON API. With redirect:"manual" an auth redirect surfaces as an
 * opaque redirect (status 0) or a 3xx; a 200 whose body is HTML (a login wall) is
 * likewise not our API. Catching this turns a misconfigured PAYMENTS_API_URL /
 * missing allowlist into a legible error instead of an opaque "(200)".
 */
function proxyAuthBounced(res: Response): boolean {
  if (res.type === "opaqueredirect") return true;
  if (res.status >= 300 && res.status < 400) return true;
  const ct = res.headers.get("content-type") || "";
  return res.ok && !ct.includes("application/json");
}

/**
 * Resolve the app's absolute origin SERVER-SIDE — no client value needed. Prefers
 * an explicit override, then NEXT_PUBLIC_APP_URL, then the incoming request's
 * forwarded host/proto (Vercel), then the Origin/Host header. This is why callers
 * must NOT pass window.location.origin: a Server Action can't read it, and a
 * missing/blank origin was the #1 cause of a failed checkout ("Invalid input").
 */
async function resolveOrigin(override?: string): Promise<string> {
  const explicit = (override || process.env.NEXT_PUBLIC_APP_URL || "").trim().replace(/\/+$/, "");
  if (explicit) return explicit;
  try {
    const h = await headers();
    const proto = (h.get("x-forwarded-proto") || "https").split(",")[0].trim();
    const host = (h.get("x-forwarded-host") || h.get("host") || "").split(",")[0].trim();
    if (host) return (proto + "://" + host).replace(/\/+$/, "");
    const originHeader = (h.get("origin") || "").trim().replace(/\/+$/, "");
    if (originHeader) return originHeader;
  } catch {
    /* headers() unavailable outside a request scope — fall through */
  }
  return "";
}

/**
 * Create a Stripe Checkout Session via the builder backend. Returns the hosted
 * url on success. NEVER throws — check result.ok, then redirect to result.url.
 * The origin is resolved SERVER-SIDE (see resolveOrigin) — do NOT pass one.
 */
export async function createCheckoutSession(
  input: CreateCheckoutInput
): Promise<CheckoutResult> {
  if (!API_URL || !API_TOKEN || !APP_ID) return { ok: false, error: NOT_CONFIGURED };
  const origin = await resolveOrigin(input.origin);
  if (!origin) return { ok: false, error: "Impossible de déterminer l'origine du site pour le paiement." };
  const successPath = input.successPath || "/checkout/success";
  const cancelPath = input.cancelPath || "/checkout/cancel";
  try {
    const res = await fetch(API_URL + "/api/apps/stripe/checkout", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + API_TOKEN,
      },
      body: JSON.stringify({
        appId: APP_ID,
        items: input.items,
        mode: input.mode || "payment",
        successUrl: origin + successPath + "?session_id={CHECKOUT_SESSION_ID}",
        cancelUrl: origin + cancelPath,
        customerEmail: input.customerEmail,
        metadata: input.metadata,
      }),
      redirect: "manual",
      cache: "no-store",
    });
    if (proxyAuthBounced(res)) return { ok: false, error: AUTH_REDIRECT_ERROR };
    const data: { url?: string; sessionId?: string; error?: string } = await res
      .json()
      .catch(() => ({}));
    if (!res.ok || typeof data.url !== "string") {
      return { ok: false, error: data.error || "Échec de la création du paiement (" + res.status + ")." };
    }
    return { ok: true, url: data.url, sessionId: typeof data.sessionId === "string" ? data.sessionId : "" };
  } catch {
    return { ok: false, error: "Service de paiement injoignable. Réessayez plus tard." };
  }
}

/**
 * Verify a Checkout Session's payment status via the builder backend (no Stripe
 * key needed). Call from the success page BEFORE fulfilling. NEVER throws — on
 * !ok render a "verification en cours, rafraîchissez" state. Fulfillment MUST be
 * idempotent (a success page can be refreshed).
 */
export async function getCheckoutStatus(sessionId: string): Promise<CheckoutStatusResult> {
  if (!API_URL || !API_TOKEN || !APP_ID) return { ok: false, error: NOT_CONFIGURED };
  if (!sessionId) return { ok: false, error: "Identifiant de session manquant." };
  try {
    const res = await fetch(API_URL + "/api/apps/stripe/session", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + API_TOKEN,
      },
      body: JSON.stringify({ appId: APP_ID, sessionId }),
      redirect: "manual",
      cache: "no-store",
    });
    if (proxyAuthBounced(res)) return { ok: false, error: AUTH_REDIRECT_ERROR };
    const data: {
      paid?: boolean;
      status?: string;
      amountTotal?: number;
      currency?: string;
      customerEmail?: string;
      metadata?: Record<string, string>;
      error?: string;
    } = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { ok: false, error: data.error || "Échec de la vérification du paiement (" + res.status + ")." };
    }
    return {
      ok: true,
      paid: data.paid === true,
      status: typeof data.status === "string" ? data.status : null,
      amountTotal: typeof data.amountTotal === "number" ? data.amountTotal : null,
      currency: typeof data.currency === "string" ? data.currency : null,
      customerEmail: typeof data.customerEmail === "string" ? data.customerEmail : null,
      metadata: data.metadata && typeof data.metadata === "object" ? data.metadata : {},
    };
  } catch {
    return { ok: false, error: "Service de paiement injoignable. Réessayez plus tard." };
  }
}
