// Auto-generated by Cobra (deterministic, 0 tokens). MONEY / CURRENCY.
// SINGLE source of truth for the app's currency + price formatting. The checkout
// items and EVERY price the UI shows MUST use these — never define a second
// formatter or a second currency (that is the "display USD, charge EUR" bug).

/** ISO 4217 code, lowercase as Stripe expects. Used for BOTH charging and display. */
export const CURRENCY = "eur";
export const CURRENCY_SYMBOL = "€";

/** Format an integer amount in the smallest unit (cents) as a localized price string. */
export function formatPrice(cents: number): string {
  return new Intl.NumberFormat("fr-FR", {
    style: "currency",
    currency: CURRENCY.toUpperCase(),
  }).format((cents || 0) / 100);
}
